import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ThemeProvider from './provider/ThemeProvider';
import Providers from './provider/Provider';

export const metadata: Metadata = {
  title: 'LoL 정보 앱',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className='h-full'>
      <body className='min-h-screen'>
        <div className='grid grid-rows-[64px_1fr_auto] h-auto'>
          <Header />
          <main className='h-auto'>
            <Providers>
              <ThemeProvider>{children}</ThemeProvider>
            </Providers>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
