import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'LoL 정보 앱',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='grid grid-rows-[80px_1fr_auto]  '>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
